<?php

function concordescouts_system_theme_registry_alter(&$theme_registry) {
  //Overrides the use of theme_date_combo()
  $theme_registry['date_combo']['function'] = 'concordescouts_system_theme_date_combo';
}

/**
 * Replacement for theme_date_combo. Doesn't return any fieldsets, or otherwise wrap
 * the date field.
 * @todo probably this is only relevent to 'single field' date widgets like the 
 * calendar popup.
 * 
 * @todo labels need to be considered. 
 */
function concordescouts_system_theme_date_combo($variables) {
  //More work needed
  return $variables['element']['#children'];
}

//@TODO when creating a programme you should be able to 'add the next 5 wednesdays'
//@TODO a programme entry should be removed if it has no 'event' description field - this is instead of making the field required.

//@TODO whenever the 'section' field is used this will need to be called
function concordescouts_system_form_programme_node_form_alter() {
  ctools_add_css('node-form', 'concordescouts_system');
}

//Alter the login form to make it difficult to login without OpenID
function concordescouts_system_form_user_login_alter(&$form, &$form_state) {

  $form['group'] = array(
    '#type' => 'fieldset',
    '#title' => 'Administrative login',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  
  $form['group']['name'] = $form['name'];
  $form['group']['pass'] = $form['pass'];
  $form['group']['actions'] = $form['actions'];
  unset($form['name'], $form['pass'], $form['actions']);
  unset($form['openid_links']);
  
  $form['login_wrapper'] = array(
    '#type' => 'item',
    '#description' => t('Group members with a 25th Medway Google Account (email address ending in @concordescouts.org.uk) are able to login to this site. Use the button above.<br />All other Google logins will be rejected.')
  );
  
  $form['login_wrapper']['login_button'] = array(
    '#validate' => array('concordescouts_system_form_user_login_validate'),
    '#type' => 'submit', 
    '#value' => t('Click here to login'),
    
  );
     
}

//Starts the openid login process.
function concordescouts_system_form_user_login_validate(&$form, &$form_state) {
  
  $return_to = $form_state['values']['openid.return_to'];
  if (empty($return_to)) {
    $return_to = url('', array('absolute' => TRUE));
  }

  openid_begin('https://www.google.com/accounts/o8/id', $return_to, $form_state['values']);
  
}




/**
 * Implements hook_form_FORM_ID_alter() for user_register_form().
 * 
 * Makes it impossible to register a user account without OpenID and prevents you 
 * from specifying an email address manually (got to use the one your given!)
 */
function concordescouts_system_form_user_register_form_alter(&$form, &$form_state) {
  $form['#validate'][] = 'concordescouts_system_user_register_form_validate';
  $form['account']['mail']['#type'] = 'value';
  $form['account']['mail']['#value'] = $form['account']['mail']['#default_value'];
  unset($form['captcha']);  
}

//Prevents signups without an OpenID value 
function concordescouts_system_user_register_form_validate(&$form, &$form_state) { 
  if (!isset($form['openid_claimed_id']) || empty($form['openid_claimed_id']['#value'])) {
    form_set_error(NULL, 'Sorry, you can only sign up with a valid OpenID');
  }
}
